# =====================
# SITE BASICS
# =====================
title: "Portfolio Theme Showcase"
description: "Professional portfolio themes for students and developers. Choose from our collection of GitHub Pages ready themes."
url: "https://abhinav9558.github.io" # ← Your actual GitHub username
baseurl: "/DAE-Demo" # ← Your actual repository name

# =====================
# THEME (Default for main site)
# =====================
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

# =====================
# AUTHOR PROFILE
# =====================
author:
    name: "DAE Portfolio Themes"
    avatar: "/assets/img/pinky.jpg"
    bio: "Professional portfolio themes for GitHub Pages"
    location: "Global"
    links:
        - label: "GitHub Repository"
          icon: "fab fa-github"
          url: "https://github.com/your-username/DAE-Demo"

# =====================
# NAVIGATION (top menu)
# =====================
# Navigation is configured in _data/navigation.yml for Minimal Mistakes theme

# =====================
# BRANDING
# =====================
logo: "/assets/img/dae-logo.jpg"

# =====================
# PLUGINS (safe + GitHub Pages supported)
# =====================
plugins:
    - jekyll-feed
    - jekyll-seo-tag
    - jekyll-include-cache
    - jekyll-remote-theme

# =====================
# COLLECTIONS & DEFAULTS
# =====================
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author_profile: true

# =====================
# SITE SETTINGS
# =====================
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: America/New_York

# =====================
# EXCLUDE
# =====================
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - node_modules/
  - README.md
  - DEPLOYMENT.md
  - Gemfile
  - Gemfile.lock
  - vendor/
  - .bundle/