# =====================
# SITE BASICS
# =====================
title: "Alex Rivera — Cybersecurity & Backend Developer"
description: "Portfolio showcasing secure backend systems, automation, and case studies."
url: "https://abhinav9558.github.io" # ← Your actual GitHub username
baseurl: "/DAE-Demo" # ← Your actual repository name

# =====================
# THEME (Default for main site)
# =====================
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

# =====================
# AUTHOR PROFILE
# =====================
author:
    name: "Alex Rivera"
    avatar: "/assets/img/pinky.jpg"
    bio: "Cybersecurity & backend developer focused on secure-by-default services."
    email: "alex.rivera@example.com"
    links:
        - label: "GitHub"
          icon: "fab fa-github"
          url: "https://github.com/your-username"
        - label: "LinkedIn"
          icon: "fab fa-linkedin"
          url: "https://www.linkedin.com/in/your-profile/"

# =====================
# NAVIGATION (top menu)
# =====================
# Navigation is configured in _data/navigation.yml for Minimal Mistakes theme

# =====================
# BRANDING
# =====================
logo: "/assets/img/dae-logo.jpg"

# =====================
# PLUGINS (safe + GitHub Pages supported)
# =====================
plugins:
    - jekyll-feed
    - jekyll-seo-tag
    - jekyll-include-cache
    - jekyll-remote-theme

# =====================
# COLLECTIONS & DEFAULTS
# =====================
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author_profile: true

# =====================
# SITE SETTINGS
# =====================
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: America/New_York

# =====================
# EXCLUDE
# =====================
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - node_modules/
  - README.md
  - theme1/
  - theme2/